# Require packages to be published for at least 3 days (4320 minutes) before installing
minimumReleaseAge: 4320

allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  # Renovate security update: esbuild@0.28.1
  - esbuild@0.28.1
